name: 'memedime'
services:
  db:
    image: postgres:18
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: memedime
      POSTGRES_PASSWORD: memedime
      POSTGRES_DB: memedime
      PGDATA: /var/lib/postgresql/data/pg18
    volumes:
        - memedime_db_data:/var/lib/postgresql/data/pg18

volumes:
  memedime_db_data:

